"""initial_domain_schema

Revision ID: 20260824_0001
Revises:
Create Date: 2026-08-24 04:40:32.361953
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Alembic renders JSONB's astext type as Text(); keep the migration self-contained.
Text = sa.Text

revision: str = "20260824_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_lmsconnection",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("base_url", sa.String(length=200), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "capabilities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("last_health_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_lmsconnection")),
        sa.UniqueConstraint("base_url", name=op.f("uq_core_lmsconnection_base_url")),
    )
    op.create_table(
        "core_course",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("external_revision", sa.String(length=255), nullable=False),
        sa.Column("sync_status", sa.String(length=32), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "policies",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["core_lmsconnection.id"],
            name=op.f("fk_core_course_connection_id_core_lmsconnection"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_course")),
        sa.UniqueConstraint("connection_id", "external_id", name="unique_course"),
    )
    with op.batch_alter_table("core_course", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_course_connection_id"), ["connection_id"], unique=False
        )

    op.create_table(
        "core_externalmapping",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("local_type", sa.String(length=64), nullable=False),
        sa.Column("local_id", sa.Uuid(), nullable=False),
        sa.Column("external_type", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("external_revision", sa.String(length=255), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["core_lmsconnection.id"],
            name=op.f("fk_core_externalmapping_connection_id_core_lmsconnection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_externalmapping")),
        sa.UniqueConstraint(
            "connection_id", "external_type", "external_id", name="unique_external_mapping"
        ),
    )
    with op.batch_alter_table("core_externalmapping", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_externalmapping_connection_id"), ["connection_id"], unique=False
        )

    op.create_table(
        "core_externalprincipal",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("external_subject", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("locale", sa.String(length=20), nullable=False),
        sa.Column("profile_revision", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "preferences",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["core_lmsconnection.id"],
            name=op.f("fk_core_externalprincipal_connection_id_core_lmsconnection"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_externalprincipal")),
        sa.UniqueConstraint("connection_id", "external_subject", name="unique_external_principal"),
    )
    with op.batch_alter_table("core_externalprincipal", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_externalprincipal_connection_id"), ["connection_id"], unique=False
        )

    op.create_table(
        "core_logintransaction",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("verifier_hash", sa.String(length=64), nullable=False),
        sa.Column("admin_requested", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["core_lmsconnection.id"],
            name=op.f("fk_core_logintransaction_connection_id_core_lmsconnection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_logintransaction")),
        sa.UniqueConstraint("state_hash", name=op.f("uq_core_logintransaction_state_hash")),
    )
    with op.batch_alter_table("core_logintransaction", schema=None) as batch_op:
        batch_op.create_index(
            "core_logint_expires_used_idx", ["expires_at", "used_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_logintransaction_connection_id"), ["connection_id"], unique=False
        )

    op.create_table(
        "core_usedlaunchnonce",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("nonce_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["core_lmsconnection.id"],
            name=op.f("fk_core_usedlaunchnonce_connection_id_core_lmsconnection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_usedlaunchnonce")),
        sa.UniqueConstraint("connection_id", "nonce_hash", name="unique_launch_nonce"),
    )
    with op.batch_alter_table("core_usedlaunchnonce", schema=None) as batch_op:
        batch_op.create_index("core_usedla_expires_idx", ["expires_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_core_usedlaunchnonce_connection_id"), ["connection_id"], unique=False
        )

    op.create_table(
        "core_adminelevation",
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("session_key", sa.String(length=80), nullable=False),
        sa.Column("token_version", sa.String(length=64), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_ip_prefix", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_adminelevation_principal_id_core_externalprincipal"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_adminelevation")),
    )
    with op.batch_alter_table("core_adminelevation", schema=None) as batch_op:
        batch_op.create_index(
            "core_admine_session_expires_idx", ["session_key", "expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_adminelevation_principal_id"), ["principal_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_adminelevation_session_key"), ["session_key"], unique=False
        )

    op.create_table(
        "core_auditentry",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("object_type", sa.String(length=100), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=True),
        sa.Column("course_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_auditentry_actor_id_core_externalprincipal"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["core_course.id"],
            name=op.f("fk_core_auditentry_course_id_core_course"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_auditentry")),
    )
    with op.batch_alter_table("core_auditentry", schema=None) as batch_op:
        batch_op.create_index(
            "core_audit_course_occurred_idx", ["course_id", "occurred_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_core_auditentry_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_core_auditentry_course_id"), ["course_id"], unique=False
        )

    op.create_table(
        "core_coursegroup",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["core_course.id"],
            name=op.f("fk_core_coursegroup_course_id_core_course"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_coursegroup")),
        sa.UniqueConstraint("course_id", "external_id", name="unique_course_group"),
    )
    with op.batch_alter_table("core_coursegroup", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_coursegroup_course_id"), ["course_id"], unique=False
        )

    op.create_table(
        "core_courseimportjob",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_id", sa.Uuid(), nullable=False),
        sa.Column("locator_hash", sa.String(length=64), nullable=False),
        sa.Column("external_course_id", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column(
            "preview",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "capability_report",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("confirmed_course_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_course_id"],
            ["core_course.id"],
            name=op.f("fk_core_courseimportjob_confirmed_course_id_core_course"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["core_lmsconnection.id"],
            name=op.f("fk_core_courseimportjob_connection_id_core_lmsconnection"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_courseimportjob_requested_by_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_courseimportjob")),
    )
    with op.batch_alter_table("core_courseimportjob", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_courseimportjob_confirmed_course_id"),
            ["confirmed_course_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_core_courseimportjob_connection_id"), ["connection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_courseimportjob_requested_by_id"), ["requested_by_id"], unique=False
        )

    op.create_table(
        "core_coursemembership",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_revision", sa.String(length=255), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["core_course.id"],
            name=op.f("fk_core_coursemembership_course_id_core_course"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_coursemembership_principal_id_core_externalprincipal"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_coursemembership")),
        sa.UniqueConstraint(
            "course_id", "principal_id", "role", name="unique_course_membership_role"
        ),
    )
    with op.batch_alter_table("core_coursemembership", schema=None) as batch_op:
        batch_op.create_index(
            "core_course_principal_role_active_idx",
            ["principal_id", "role", "active"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_core_coursemembership_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_coursemembership_principal_id"), ["principal_id"], unique=False
        )

    op.create_table(
        "core_coursesection",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("external_revision", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["core_course.id"],
            name=op.f("fk_core_coursesection_course_id_core_course"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_coursesection")),
        sa.UniqueConstraint("course_id", "external_id", name="unique_course_section"),
    )
    with op.batch_alter_table("core_coursesection", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_coursesection_course_id"), ["course_id"], unique=False
        )

    op.create_table(
        "core_principalsession",
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent_hash", sa.String(length=64), nullable=False),
        sa.Column("request_ip_prefix", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_principalsession_principal_id_core_externalprincipal"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_principalsession")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_core_principalsession_token_hash")),
    )
    with op.batch_alter_table("core_principalsession", schema=None) as batch_op:
        batch_op.create_index(
            "core_principalsession_expires_revoked_idx", ["expires_at", "revoked_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_principalsession_principal_id"), ["principal_id"], unique=False
        )

    op.create_table(
        "core_systemsetting",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_by_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_systemsetting_updated_by_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_systemsetting")),
        sa.UniqueConstraint("key", name=op.f("uq_core_systemsetting_key")),
    )
    with op.batch_alter_table("core_systemsetting", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_systemsetting_updated_by_id"), ["updated_by_id"], unique=False
        )

    op.create_table(
        "core_taskbankitem",
        sa.Column("scope", sa.String(length=10), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=True),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["core_course.id"],
            name=op.f("fk_core_taskbankitem_course_id_core_course"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_taskbankitem_created_by_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_taskbankitem")),
        sa.UniqueConstraint("course_id", "slug", name="unique_course_task_slug"),
    )
    with op.batch_alter_table("core_taskbankitem", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_taskbankitem_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_taskbankitem_created_by_id"), ["created_by_id"], unique=False
        )

    op.create_table(
        "core_assessment",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("attempt_limit", sa.SmallInteger(), nullable=False),
        sa.Column("max_score", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("paste_policy", sa.String(length=32), nullable=False),
        sa.Column("student_ai_enabled", sa.Boolean(), nullable=False),
        sa.Column("teacher_ai_enabled", sa.Boolean(), nullable=False),
        sa.Column("autosubmit", sa.Boolean(), nullable=False),
        sa.Column("multi_file", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "policy",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["core_course.id"],
            name=op.f("fk_core_assessment_course_id_core_course"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_assessment_created_by_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["core_coursesection.id"],
            name=op.f("fk_core_assessment_section_id_core_coursesection"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_assessment")),
    )
    with op.batch_alter_table("core_assessment", schema=None) as batch_op:
        batch_op.create_index(
            "core_assess_course_status_opens_idx", ["course_id", "status", "opens_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_assessment_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_assessment_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_assessment_section_id"), ["section_id"], unique=False
        )

    op.create_table(
        "core_coursemembership_groups",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("coursemembership_id", sa.Uuid(), nullable=False),
        sa.Column("coursegroup_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coursegroup_id"],
            ["core_coursegroup.id"],
            name=op.f("fk_core_coursemembership_groups_coursegroup_id_core_coursegroup"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["coursemembership_id"],
            ["core_coursemembership.id"],
            name=op.f("fk_core_coursemembership_groups_coursemembership_id_core_coursemembership"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_coursemembership_groups")),
        sa.UniqueConstraint(
            "coursemembership_id", "coursegroup_id", name="unique_course_membership_group"
        ),
    )
    with op.batch_alter_table("core_coursemembership_groups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_coursemembership_groups_coursegroup_id"),
            ["coursegroup_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_core_coursemembership_groups_coursemembership_id"),
            ["coursemembership_id"],
            unique=False,
        )

    op.create_table(
        "core_taskversion",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("language_standard", sa.String(length=20), nullable=False),
        sa.Column("multi_file", sa.Boolean(), nullable=False),
        sa.Column(
            "starter_files",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("build_profile", sa.String(length=100), nullable=False),
        sa.Column(
            "public_examples",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "hidden_test_manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("max_score", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("difficulty", sa.String(length=32), nullable=False),
        sa.Column(
            "ai_policy",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("authored_by_id", sa.Uuid(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["authored_by_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_taskversion_authored_by_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["core_taskbankitem.id"],
            name=op.f("fk_core_taskversion_item_id_core_taskbankitem"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_taskversion")),
        sa.UniqueConstraint("item_id", "number", name="unique_task_version"),
    )
    with op.batch_alter_table("core_taskversion", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_taskversion_authored_by_id"), ["authored_by_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_core_taskversion_item_id"), ["item_id"], unique=False)

    op.create_table(
        "core_assessmentitem",
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("task_version_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("points", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "assignment_rule",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["core_assessment.id"],
            name=op.f("fk_core_assessmentitem_assessment_id_core_assessment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_version_id"],
            ["core_taskversion.id"],
            name=op.f("fk_core_assessmentitem_task_version_id_core_taskversion"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_assessmentitem")),
    )
    with op.batch_alter_table("core_assessmentitem", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_assessmentitem_assessment_id"), ["assessment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_assessmentitem_task_version_id"), ["task_version_id"], unique=False
        )

    op.create_table(
        "core_attempt",
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_task_version_id", sa.Uuid(), nullable=True),
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.SmallInteger(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_revision", sa.BigInteger(), nullable=False),
        sa.Column("epoch", sa.SmallInteger(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submission_source", sa.String(length=32), nullable=False),
        sa.Column("reopen_reason", sa.Text(), nullable=False),
        sa.Column(
            "integrity_policy",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["core_assessment.id"],
            name=op.f("fk_core_attempt_assessment_id_core_assessment"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_task_version_id"],
            ["core_taskversion.id"],
            name=op.f("fk_core_attempt_assigned_task_version_id_core_taskversion"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_attempt_principal_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_attempt")),
        sa.UniqueConstraint(
            "assessment_id", "principal_id", "sequence", name="unique_attempt_sequence"
        ),
    )
    with op.batch_alter_table("core_attempt", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_attempt_assessment_id"), ["assessment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_attempt_assigned_task_version_id"),
            ["assigned_task_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_core_attempt_principal_id"), ["principal_id"], unique=False
        )

    op.create_table(
        "core_availabilityrule",
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_external_id", sa.String(length=255), nullable=False),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("authored_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["core_assessment.id"],
            name=op.f("fk_core_availabilityrule_assessment_id_core_assessment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["authored_by_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_availabilityrule_authored_by_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_availabilityrule")),
    )
    with op.batch_alter_table("core_availabilityrule", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_availabilityrule_assessment_id"), ["assessment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_availabilityrule_authored_by_id"), ["authored_by_id"], unique=False
        )

    op.create_table(
        "core_similarityanalysis",
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("task_version_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_id", sa.Uuid(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("submission_count", sa.Integer(), nullable=False),
        sa.Column("comparison_count", sa.Integer(), nullable=False),
        sa.Column("match_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["core_assessment.id"],
            name=op.f("fk_core_similarityanalysis_assessment_id_core_assessment"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_similarityanalysis_requested_by_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_version_id"],
            ["core_taskversion.id"],
            name=op.f("fk_core_similarityanalysis_task_version_id_core_taskversion"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_similarityanalysis")),
    )
    with op.batch_alter_table("core_similarityanalysis", schema=None) as batch_op:
        batch_op.create_index(
            "core_similarity_assessment_task_created_idx",
            ["assessment_id", "task_version_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_core_similarityanalysis_assessment_id"), ["assessment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_similarityanalysis_requested_by_id"),
            ["requested_by_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_core_similarityanalysis_task_version_id"),
            ["task_version_id"],
            unique=False,
        )

    op.create_table(
        "core_syncoutbox",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=True),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "receipt",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["core_attempt.id"],
            name=op.f("fk_core_syncoutbox_attempt_id_core_attempt"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["core_lmsconnection.id"],
            name=op.f("fk_core_syncoutbox_connection_id_core_lmsconnection"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["core_course.id"],
            name=op.f("fk_core_syncoutbox_course_id_core_course"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_syncoutbox")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_core_syncoutbox_idempotency_key")),
    )
    with op.batch_alter_table("core_syncoutbox", schema=None) as batch_op:
        batch_op.create_index(
            "core_syncout_attempt_event_created_idx",
            ["attempt_id", "event_type", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "core_syncout_course_state_created_idx",
            ["course_id", "state", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "core_syncout_state_next_idx", ["state", "next_attempt_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_syncoutbox_attempt_id"), ["attempt_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_syncoutbox_connection_id"), ["connection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_syncoutbox_course_id"), ["course_id"], unique=False
        )

    op.create_table(
        "core_workspace",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("current_revision", sa.BigInteger(), nullable=False),
        sa.Column("current_hash", sa.String(length=64), nullable=False),
        sa.Column("multi_file", sa.Boolean(), nullable=False),
        sa.Column("aggregate_size", sa.BigInteger(), nullable=False),
        sa.Column("event_chain_head", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["core_attempt.id"],
            name=op.f("fk_core_workspace_attempt_id_core_attempt"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_workspace")),
        sa.UniqueConstraint("attempt_id", name=op.f("uq_core_workspace_attempt_id")),
    )
    op.create_table(
        "core_snapshot",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("event_chain_head", sa.String(length=64), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "files",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["core_workspace.id"],
            name=op.f("fk_core_snapshot_workspace_id_core_workspace"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_snapshot")),
        sa.UniqueConstraint("workspace_id", "revision", name="unique_snapshot_revision"),
    )
    with op.batch_alter_table("core_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_snapshot_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "core_workspacefile",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_revision", sa.BigInteger(), nullable=False),
        sa.Column("deleted_revision", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["core_workspace.id"],
            name=op.f("fk_core_workspacefile_workspace_id_core_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_workspacefile")),
        sa.UniqueConstraint("workspace_id", "path", name="unique_workspace_path"),
    )
    with op.batch_alter_table("core_workspacefile", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_workspacefile_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "core_clipboardreceipt",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("text_length", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["core_attempt.id"],
            name=op.f("fk_core_clipboardreceipt_attempt_id_core_attempt"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["core_workspacefile.id"],
            name=op.f("fk_core_clipboardreceipt_file_id_core_workspacefile"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_clipboardreceipt_principal_id_core_externalprincipal"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_clipboardreceipt")),
    )
    with op.batch_alter_table("core_clipboardreceipt", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_clipboardreceipt_attempt_id"), ["attempt_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_clipboardreceipt_file_id"), ["file_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_clipboardreceipt_principal_id"), ["principal_id"], unique=False
        )

    op.create_table(
        "core_editevent",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("epoch", sa.SmallInteger(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("client_id", sa.String(length=100), nullable=False),
        sa.Column("client_request_id", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column(
            "changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["core_workspacefile.id"],
            name=op.f("fk_core_editevent_file_id_core_workspacefile"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["core_workspace.id"],
            name=op.f("fk_core_editevent_workspace_id_core_workspace"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_editevent")),
        sa.UniqueConstraint(
            "workspace_id", "client_request_id", name="unique_workspace_client_request"
        ),
        sa.UniqueConstraint("workspace_id", "sequence", name="unique_event_sequence"),
    )
    with op.batch_alter_table("core_editevent", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_core_editevent_file_id"), ["file_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_core_editevent_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "core_submission",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.SmallInteger(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("late", sa.Boolean(), nullable=False),
        sa.Column("lms_export_state", sa.String(length=32), nullable=False),
        sa.Column(
            "external_receipt",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["core_attempt.id"],
            name=op.f("fk_core_submission_attempt_id_core_attempt"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["core_snapshot.id"],
            name=op.f("fk_core_submission_snapshot_id_core_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_submission")),
        sa.UniqueConstraint("attempt_id", "revision", name="unique_submission_revision"),
    )
    with op.batch_alter_table("core_submission", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_submission_attempt_id"), ["attempt_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_submission_snapshot_id"), ["snapshot_id"], unique=False
        )

    op.create_table(
        "core_authorshipanalysisjob",
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_id", sa.Uuid(), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("export_schema_version", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_authorshipanalysisjob_requested_by_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["core_submission.id"],
            name=op.f("fk_core_authorshipanalysisjob_submission_id_core_submission"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_authorshipanalysisjob")),
    )
    with op.batch_alter_table("core_authorshipanalysisjob", schema=None) as batch_op:
        batch_op.create_index(
            "core_author_submission_state_created_idx",
            ["submission_id", "state", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_core_authorshipanalysisjob_requested_by_id"),
            ["requested_by_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_core_authorshipanalysisjob_submission_id"),
            ["submission_id"],
            unique=False,
        )

    op.create_table(
        "core_chatthread",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("submission_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["core_attempt.id"],
            name=op.f("fk_core_chatthread_attempt_id_core_attempt"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["core_course.id"],
            name=op.f("fk_core_chatthread_course_id_core_course"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_chatthread_owner_id_core_externalprincipal"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["core_submission.id"],
            name=op.f("fk_core_chatthread_submission_id_core_submission"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_chatthread")),
    )
    with op.batch_alter_table("core_chatthread", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_chatthread_attempt_id"), ["attempt_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_chatthread_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_core_chatthread_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_core_chatthread_submission_id"), ["submission_id"], unique=False
        )

    op.create_table(
        "core_reviewclaim",
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("takeover_reason", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_reviewclaim_owner_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["core_submission.id"],
            name=op.f("fk_core_reviewclaim_submission_id_core_submission"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_reviewclaim")),
    )
    with op.batch_alter_table("core_reviewclaim", schema=None) as batch_op:
        batch_op.create_index(
            "core_review_submission_state_lease_idx",
            ["submission_id", "state", "lease_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_core_reviewclaim_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_reviewclaim_submission_id"), ["submission_id"], unique=False
        )
        batch_op.create_index(
            "one_active_review_claim_per_submission",
            ["submission_id"],
            unique=True,
            postgresql_where=sa.text("state = 'ACTIVE'"),
            sqlite_where=sa.text("state = 'ACTIVE'"),
        )

    op.create_table(
        "core_reviewdecision",
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("grade", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "criterion_scores",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "evidence_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("lms_export_state", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_reviewdecision_reviewer_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["core_submission.id"],
            name=op.f("fk_core_reviewdecision_submission_id_core_submission"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["core_reviewdecision.id"],
            name=op.f("fk_core_reviewdecision_supersedes_id_core_reviewdecision"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_reviewdecision")),
        sa.UniqueConstraint("submission_id", "revision", name="unique_decision_revision"),
    )
    with op.batch_alter_table("core_reviewdecision", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_reviewdecision_reviewer_id"), ["reviewer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_reviewdecision_submission_id"), ["submission_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_reviewdecision_supersedes_id"), ["supersedes_id"], unique=False
        )

    op.create_table(
        "core_reviewdraft",
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("grade", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "criterion_scores",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_reviewdraft_owner_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["core_submission.id"],
            name=op.f("fk_core_reviewdraft_submission_id_core_submission"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_reviewdraft")),
        sa.UniqueConstraint("submission_id", name=op.f("uq_core_reviewdraft_submission_id")),
    )
    with op.batch_alter_table("core_reviewdraft", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_reviewdraft_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "core_similaritymatch",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("submission_a_id", sa.Uuid(), nullable=False),
        sa.Column("submission_b_id", sa.Uuid(), nullable=False),
        sa.Column("manifest_hash_a", sa.String(length=64), nullable=False),
        sa.Column("manifest_hash_b", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("fingerprint_count_a", sa.Integer(), nullable=False),
        sa.Column("fingerprint_count_b", sa.Integer(), nullable=False),
        sa.Column("shared_fingerprint_count", sa.Integer(), nullable=False),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "score >= 0 AND score <= 1",
            name=op.f("ck_core_similaritymatch_similarity_score_between_zero_and_one"),
        ),
        sa.CheckConstraint(
            "submission_a_id <> submission_b_id",
            name=op.f("ck_core_similaritymatch_similarity_pair_uses_distinct_submissions"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["core_similarityanalysis.id"],
            name=op.f("fk_core_similaritymatch_analysis_id_core_similarityanalysis"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_a_id"],
            ["core_submission.id"],
            name=op.f("fk_core_similaritymatch_submission_a_id_core_submission"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submission_b_id"],
            ["core_submission.id"],
            name=op.f("fk_core_similaritymatch_submission_b_id_core_submission"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_similaritymatch")),
        sa.UniqueConstraint(
            "analysis_id",
            "submission_a_id",
            "submission_b_id",
            name="unique_similarity_pair_per_analysis",
        ),
    )
    with op.batch_alter_table("core_similaritymatch", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_similaritymatch_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_similaritymatch_submission_a_id"), ["submission_a_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_similaritymatch_submission_b_id"), ["submission_b_id"], unique=False
        )

    op.create_table(
        "core_teacherexperiment",
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("base_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_teacherexperiment_owner_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["core_submission.id"],
            name=op.f("fk_core_teacherexperiment_submission_id_core_submission"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_teacherexperiment")),
    )
    with op.batch_alter_table("core_teacherexperiment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_teacherexperiment_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_teacherexperiment_submission_id"), ["submission_id"], unique=False
        )

    op.create_table(
        "core_authorshipanalysisresult",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("probability", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("uncertainty", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("analyzer", sa.String(length=200), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column(
            "calibration",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "features",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "warnings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("response_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f(
                "ck_core_authorshipanalysisresult_authorship_confidence_between_zero_and_one"
            ),
        ),
        sa.CheckConstraint(
            "probability >= 0 AND probability <= 1",
            name=op.f(
                "ck_core_authorshipanalysisresult_authorship_probability_between_zero_and_one"
            ),
        ),
        sa.CheckConstraint(
            "uncertainty >= 0 AND uncertainty <= 1",
            name=op.f(
                "ck_core_authorshipanalysisresult_authorship_uncertainty_between_zero_and_one"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["core_authorshipanalysisjob.id"],
            name=op.f("fk_core_authorshipanalysisresult_job_id_core_authorshipanalysisjob"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_authorshipanalysisresult")),
        sa.UniqueConstraint("job_id", name=op.f("uq_core_authorshipanalysisresult_job_id")),
    )
    op.create_table(
        "core_chatmessage",
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "citations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("safety_outcome", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["core_chatthread.id"],
            name=op.f("fk_core_chatmessage_thread_id_core_chatthread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_chatmessage")),
    )
    with op.batch_alter_table("core_chatmessage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_chatmessage_thread_id"), ["thread_id"], unique=False
        )

    op.create_table(
        "core_plagiarismcase",
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("teacher_comment", sa.Text(), nullable=False),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("state_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["core_similaritymatch.id"],
            name=op.f("fk_core_plagiarismcase_match_id_core_similaritymatch"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_plagiarismcase_updated_by_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_plagiarismcase")),
        sa.UniqueConstraint("match_id", name=op.f("uq_core_plagiarismcase_match_id")),
    )
    with op.batch_alter_table("core_plagiarismcase", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_plagiarismcase_updated_by_id"), ["updated_by_id"], unique=False
        )

    op.create_table(
        "core_runrequest",
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("submission_id", sa.Uuid(), nullable=True),
        sa.Column("teacher_experiment_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("build_profile", sa.String(length=100), nullable=False),
        sa.Column("filesystem_profile", sa.String(length=100), nullable=False),
        sa.Column("network_enabled", sa.Boolean(), nullable=False),
        sa.Column("stdin", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("external_job_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["core_attempt.id"],
            name=op.f("fk_core_runrequest_attempt_id_core_attempt"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["core_externalprincipal.id"],
            name=op.f("fk_core_runrequest_requested_by_id_core_externalprincipal"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["core_submission.id"],
            name=op.f("fk_core_runrequest_submission_id_core_submission"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_experiment_id"],
            ["core_teacherexperiment.id"],
            name=op.f("fk_core_runrequest_teacher_experiment_id_core_teacherexperiment"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_runrequest")),
    )
    with op.batch_alter_table("core_runrequest", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_runrequest_attempt_id"), ["attempt_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_runrequest_requested_by_id"), ["requested_by_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_runrequest_submission_id"), ["submission_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_runrequest_teacher_experiment_id"),
            ["teacher_experiment_id"],
            unique=False,
        )

    op.create_table(
        "core_teacherexperimentfile",
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["core_teacherexperiment.id"],
            name=op.f("fk_core_teacherexperimentfile_experiment_id_core_teacherexperiment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_teacherexperimentfile")),
        sa.UniqueConstraint("experiment_id", "path", name="unique_experiment_path"),
    )
    with op.batch_alter_table("core_teacherexperimentfile", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_teacherexperimentfile_experiment_id"),
            ["experiment_id"],
            unique=False,
        )

    op.create_table(
        "core_runresult",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("exit_reason", sa.String(length=64), nullable=False),
        sa.Column("stdout", sa.Text(), nullable=False),
        sa.Column("stderr", sa.Text(), nullable=False),
        sa.Column(
            "diagnostics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("executor_version", sa.String(length=100), nullable=False),
        sa.Column("filesystem_policy_version", sa.String(length=100), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["core_runrequest.id"],
            name=op.f("fk_core_runresult_run_id_core_runrequest"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_runresult")),
        sa.UniqueConstraint("run_id", name=op.f("uq_core_runresult_run_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("core_runresult")
    with op.batch_alter_table("core_teacherexperimentfile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_teacherexperimentfile_experiment_id"))

    op.drop_table("core_teacherexperimentfile")
    with op.batch_alter_table("core_runrequest", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_runrequest_teacher_experiment_id"))
        batch_op.drop_index(batch_op.f("ix_core_runrequest_submission_id"))
        batch_op.drop_index(batch_op.f("ix_core_runrequest_requested_by_id"))
        batch_op.drop_index(batch_op.f("ix_core_runrequest_attempt_id"))

    op.drop_table("core_runrequest")
    with op.batch_alter_table("core_plagiarismcase", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_plagiarismcase_updated_by_id"))

    op.drop_table("core_plagiarismcase")
    with op.batch_alter_table("core_chatmessage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_chatmessage_thread_id"))

    op.drop_table("core_chatmessage")
    op.drop_table("core_authorshipanalysisresult")
    with op.batch_alter_table("core_teacherexperiment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_teacherexperiment_submission_id"))
        batch_op.drop_index(batch_op.f("ix_core_teacherexperiment_owner_id"))

    op.drop_table("core_teacherexperiment")
    with op.batch_alter_table("core_similaritymatch", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_similaritymatch_submission_b_id"))
        batch_op.drop_index(batch_op.f("ix_core_similaritymatch_submission_a_id"))
        batch_op.drop_index(batch_op.f("ix_core_similaritymatch_analysis_id"))

    op.drop_table("core_similaritymatch")
    with op.batch_alter_table("core_reviewdraft", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_reviewdraft_owner_id"))

    op.drop_table("core_reviewdraft")
    with op.batch_alter_table("core_reviewdecision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_reviewdecision_supersedes_id"))
        batch_op.drop_index(batch_op.f("ix_core_reviewdecision_submission_id"))
        batch_op.drop_index(batch_op.f("ix_core_reviewdecision_reviewer_id"))

    op.drop_table("core_reviewdecision")
    with op.batch_alter_table("core_reviewclaim", schema=None) as batch_op:
        batch_op.drop_index(
            "one_active_review_claim_per_submission",
            postgresql_where=sa.text("state = 'ACTIVE'"),
            sqlite_where=sa.text("state = 'ACTIVE'"),
        )
        batch_op.drop_index(batch_op.f("ix_core_reviewclaim_submission_id"))
        batch_op.drop_index(batch_op.f("ix_core_reviewclaim_owner_id"))
        batch_op.drop_index("core_review_submission_state_lease_idx")

    op.drop_table("core_reviewclaim")
    with op.batch_alter_table("core_chatthread", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_chatthread_submission_id"))
        batch_op.drop_index(batch_op.f("ix_core_chatthread_owner_id"))
        batch_op.drop_index(batch_op.f("ix_core_chatthread_course_id"))
        batch_op.drop_index(batch_op.f("ix_core_chatthread_attempt_id"))

    op.drop_table("core_chatthread")
    with op.batch_alter_table("core_authorshipanalysisjob", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_authorshipanalysisjob_submission_id"))
        batch_op.drop_index(batch_op.f("ix_core_authorshipanalysisjob_requested_by_id"))
        batch_op.drop_index("core_author_submission_state_created_idx")

    op.drop_table("core_authorshipanalysisjob")
    with op.batch_alter_table("core_submission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_submission_snapshot_id"))
        batch_op.drop_index(batch_op.f("ix_core_submission_attempt_id"))

    op.drop_table("core_submission")
    with op.batch_alter_table("core_editevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_editevent_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_core_editevent_file_id"))

    op.drop_table("core_editevent")
    with op.batch_alter_table("core_clipboardreceipt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_clipboardreceipt_principal_id"))
        batch_op.drop_index(batch_op.f("ix_core_clipboardreceipt_file_id"))
        batch_op.drop_index(batch_op.f("ix_core_clipboardreceipt_attempt_id"))

    op.drop_table("core_clipboardreceipt")
    with op.batch_alter_table("core_workspacefile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_workspacefile_workspace_id"))

    op.drop_table("core_workspacefile")
    with op.batch_alter_table("core_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_snapshot_workspace_id"))

    op.drop_table("core_snapshot")
    op.drop_table("core_workspace")
    with op.batch_alter_table("core_syncoutbox", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_syncoutbox_course_id"))
        batch_op.drop_index(batch_op.f("ix_core_syncoutbox_connection_id"))
        batch_op.drop_index(batch_op.f("ix_core_syncoutbox_attempt_id"))
        batch_op.drop_index("core_syncout_state_next_idx")
        batch_op.drop_index("core_syncout_course_state_created_idx")
        batch_op.drop_index("core_syncout_attempt_event_created_idx")

    op.drop_table("core_syncoutbox")
    with op.batch_alter_table("core_similarityanalysis", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_similarityanalysis_task_version_id"))
        batch_op.drop_index(batch_op.f("ix_core_similarityanalysis_requested_by_id"))
        batch_op.drop_index(batch_op.f("ix_core_similarityanalysis_assessment_id"))
        batch_op.drop_index("core_similarity_assessment_task_created_idx")

    op.drop_table("core_similarityanalysis")
    with op.batch_alter_table("core_availabilityrule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_availabilityrule_authored_by_id"))
        batch_op.drop_index(batch_op.f("ix_core_availabilityrule_assessment_id"))

    op.drop_table("core_availabilityrule")
    with op.batch_alter_table("core_attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_attempt_principal_id"))
        batch_op.drop_index(batch_op.f("ix_core_attempt_assigned_task_version_id"))
        batch_op.drop_index(batch_op.f("ix_core_attempt_assessment_id"))

    op.drop_table("core_attempt")
    with op.batch_alter_table("core_assessmentitem", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_assessmentitem_task_version_id"))
        batch_op.drop_index(batch_op.f("ix_core_assessmentitem_assessment_id"))

    op.drop_table("core_assessmentitem")
    with op.batch_alter_table("core_taskversion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_taskversion_item_id"))
        batch_op.drop_index(batch_op.f("ix_core_taskversion_authored_by_id"))

    op.drop_table("core_taskversion")
    with op.batch_alter_table("core_coursemembership_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_coursemembership_groups_coursemembership_id"))
        batch_op.drop_index(batch_op.f("ix_core_coursemembership_groups_coursegroup_id"))

    op.drop_table("core_coursemembership_groups")
    with op.batch_alter_table("core_assessment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_assessment_section_id"))
        batch_op.drop_index(batch_op.f("ix_core_assessment_created_by_id"))
        batch_op.drop_index(batch_op.f("ix_core_assessment_course_id"))
        batch_op.drop_index("core_assess_course_status_opens_idx")

    op.drop_table("core_assessment")
    with op.batch_alter_table("core_taskbankitem", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_taskbankitem_created_by_id"))
        batch_op.drop_index(batch_op.f("ix_core_taskbankitem_course_id"))

    op.drop_table("core_taskbankitem")
    with op.batch_alter_table("core_systemsetting", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_systemsetting_updated_by_id"))

    op.drop_table("core_systemsetting")
    with op.batch_alter_table("core_principalsession", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_principalsession_principal_id"))
        batch_op.drop_index("core_principalsession_expires_revoked_idx")

    op.drop_table("core_principalsession")
    with op.batch_alter_table("core_coursesection", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_coursesection_course_id"))

    op.drop_table("core_coursesection")
    with op.batch_alter_table("core_coursemembership", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_coursemembership_principal_id"))
        batch_op.drop_index(batch_op.f("ix_core_coursemembership_course_id"))
        batch_op.drop_index("core_course_principal_role_active_idx")

    op.drop_table("core_coursemembership")
    with op.batch_alter_table("core_courseimportjob", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_courseimportjob_requested_by_id"))
        batch_op.drop_index(batch_op.f("ix_core_courseimportjob_connection_id"))
        batch_op.drop_index(batch_op.f("ix_core_courseimportjob_confirmed_course_id"))

    op.drop_table("core_courseimportjob")
    with op.batch_alter_table("core_coursegroup", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_coursegroup_course_id"))

    op.drop_table("core_coursegroup")
    with op.batch_alter_table("core_auditentry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_auditentry_course_id"))
        batch_op.drop_index(batch_op.f("ix_core_auditentry_actor_id"))
        batch_op.drop_index("core_audit_course_occurred_idx")

    op.drop_table("core_auditentry")
    with op.batch_alter_table("core_adminelevation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_adminelevation_session_key"))
        batch_op.drop_index(batch_op.f("ix_core_adminelevation_principal_id"))
        batch_op.drop_index("core_admine_session_expires_idx")

    op.drop_table("core_adminelevation")
    with op.batch_alter_table("core_usedlaunchnonce", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_usedlaunchnonce_connection_id"))
        batch_op.drop_index("core_usedla_expires_idx")

    op.drop_table("core_usedlaunchnonce")
    with op.batch_alter_table("core_logintransaction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_logintransaction_connection_id"))
        batch_op.drop_index("core_logint_expires_used_idx")

    op.drop_table("core_logintransaction")
    with op.batch_alter_table("core_externalprincipal", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_externalprincipal_connection_id"))

    op.drop_table("core_externalprincipal")
    with op.batch_alter_table("core_externalmapping", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_externalmapping_connection_id"))

    op.drop_table("core_externalmapping")
    with op.batch_alter_table("core_course", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_course_connection_id"))

    op.drop_table("core_course")
    op.drop_table("core_lmsconnection")
    # ### end Alembic commands ###
